### ISSUE TITLE
Use source ip not specified in config

### ISSUE THREAD

**Issue by Surya361** [citrix/kube-ingress-citrix-netscaler#1]
use source ip is not set when adding a service, which is deafulting to true on the netscaler, and since the vip is not bound on the container return packets from the container are not reaching.

ep_ip_port := strings.Split(IpPort, ":")
	servicePort, _ := strconv.Atoi(ep_ip_port[1])
	nsService := basic.Service{
		Name:        sname,
		Ip:          ep_ip_port[0],
		Servicetype: "HTTP",
		Port:        servicePort,
	}
	_, err := client.AddResource(netscaler.Service.Type(), sname, &nsService)

**Comment by chiradeep** [comment]
Not sure I understand. Are you talking about USIP or USNIP? USIP won't work in this scenario.

https://support.citrix.com/article/CTX121974/

**Comment by Surya361** [comment]
its usip, looks like netscaler by default is setting it to true, and since a loopback device is not mounted on the kube pods thd DSR is not working

**Comment by chiradeep** [comment]
That's not the code. Somebody else must have configured it so.

To globally enable or disable USIP mode by using the command line interface

At the command prompt, type the following commands:

disable ns mode USIP

**Comment by Surya361** [comment]
out of context question
Are you guys actively developing this, i cannot see support for https, tcp endpoints

**Comment by chiradeep** [comment]
We have another integration using NetScaler MAS (http://docs.citrix.com/en-us/netscaler-mas/12.html). That adds more sophisticated configuration capabilities and deep analytics. But we will continue to develop this integration if there is interest (for e.g., using it in Cloud, or folks that do not want MAS). Let us know if you want to collaborate.

**Comment by chiradeep** [comment]
is this still an issue?
